services:
  memphis-metadata:
    image: memphisos/memphis-metadata:docker-15.2.0-debian-11-r27
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memphis -p 5005"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - memphis
    ports:
      - '5005:5005'
    environment:
      - POSTGRESQL_USERNAME=memphis
      - POSTGRESQL_PASSWORD=memphis
      - POSTGRESQL_DATABASE=memphis
      - POSTGRESQL_PORT_NUMBER=5005
  memphis:
    image: "memphisos/memphis:latest"
    depends_on:
      memphis-metadata:
        condition: service_healthy
    healthcheck:
      test: wget http://127.0.0.1:9000 --spider || exit 1
      interval: 10s
      retries: 30
      start_period: 5s
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "9000:9000"
      - "6666:6666"
      - "7770:7770"
    environment:
      - ROOT_PASSWORD=memphis
      - DOCKER_ENV=true
      - USER_PASS_BASED_AUTH=true
      - CONNECTION_TOKEN=memphis
      - METADATA_DB_HOST=memphis-metadata
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  memphis-protocol-adapter:
    image: "g41797/memphis-protocol-adapter:latest"
    depends_on:
      memphis:
        condition: service_healthy
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "5141:5141/tcp"
      - "5143:5143/tcp"
      - "5141:5141/udp"
    environment:
          - MEMPHIS_ADDR=memphis:6666
          - MEMPHIS_HOST=memphis
          - ADDRTCP=0.0.0.0:5141
          - ADDRUDP=0.0.0.0:5141
          - ADDRTLS=0.0.0.0:5143

networks:
  memphis:
    ipam:
      driver: default
